name: Build Documentation

on:
  push:
    branches:
      - main # Trigger on pushes to the default branch
  workflow_dispatch:        # Allow manual triggering of the workflow from the GitHub Actions interface

# Cancel previous runs if a new commit is pushed to the same PR or branch
concurrency:
  group: ${{ github.ref }}  # Group runs by the ref (branch or PR)
  cancel-in-progress: true  # Cancel any ongoing runs in the same group

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build documentation
    steps:
      - name: Cleanup to free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout project
        uses: actions/checkout@v6 # v6.0.0
        with:
          fetch-depth: 1
          
      - name: Build project
        uses: leanprover/lean-action@65f454bc22ec83143241456eee965c2ab702ba6e # 2026-01-15
        with:
          build: true
          lint: false
          mk_all-check: false
      
      - name: Build Verso Documentation
        run: |
          ./build_manual.sh
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: html